<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->char('code', 2);
            $table->string('name', 200);
            $table->string('name_en', 200);
            $table->tinyInteger('eu')->default(0);
            $table->tinyInteger('sort')->default(0);
        });
        
        foreach(self::getCountries() as $country)
        {
            DB::table('countries')->insert(
                array(
                    'code' => $country[0],
                    'name' => $country[1],
                    'name_en' => $country[2],
                    'eu' => !empty($country[3]) ? 1 : 0,
                    'sort' => !empty($country[4]) ? 1 : 0,
                )
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
    
    
    private static function getCountries()
    {
        return [
            ["AF", "Afganistan", "Afghanistan"],
            ["AL", "Albania", "Albania"],
            ["DZ", "Algieria", "Algeria"],
            ["AD" ,"Andora", "Andorra"],
            ["AO", "Angola", "Angola"],
            ["AI", "Anguilla", "Anguilla"],
            ["AQ", "Antarktyda", "Antarctica"],
            ["AG", "Antigua i Barbuda", "Antigua and Barbuda"],
            ["SA", "Arabia Saudyjska", "Saudi Arabia"],
            ["AR", "Argentyna", "Argentina"],
            ["AM", "Armenia", "Armenia"],
            ["AW", "Aruba", "Aruba"],
            ["AU", "Australia", "Australia"],
            ["AT", "Austria", "Austria", 1],
            ["AZ", "Azerbejdżan", "Azerbaijan"],
            ["BS", "Bahamy", "Bahamas"],
            ["BH", "Bahrajn", "Bahrain"],
            ["BD", "Bangladesz","Bangladesh"],
            ["BB", "Barbados", "Barbados"],
            ["BE", "Belgia", "Belgium", 1],
            ["BZ", "Belize", "Belize"],
            ["BJ", "Benin", "Benin"],
            ["BM", "Bermudy", "Bermuda"],
            ["BT", "Bhutan", "Bhutan"],
            ["BY", "Białoruś", "Belarus"],
            ["BO", "Boliwia", "Bolivia"],
            ["BQ", "Bonaire, Sint Eustatius i Saba", "Bonaire, Sint Eustatius and Saba"],
            ["BA", "Bośnia i Hercegowina", "Bosnia and Herzegovina"],
            ["BW", "Botswana", "Botswana"],
            ["BR", "Brazylia", "Brazil"],
            ["BN", "Brunei Darussalam", "Brunei Darussalam"],
            ["IO", "Brytyjskie Terytorium Oceanu Indyjskiego", "British Indian Ocean Territory"],
            ["BG", "Bułgaria", "Bulgaria", 1],
            ["BF", "Burkina Faso", "Burkina Faso"],
            ["BI", "Burundi", "Burundi"],
            ["XC", "Ceuta", "Ceuta"],
            ["CL", "Chile", "Chile"],
            ["CN", "Chiny", "China"],
            ["CW", "Curaçao", "Curaçao"],
            ["HR", "Chorwacja", "Croatia", 1],
            ["CY", "Cypr", "Cyprus", 1],
            ["TD", "Czad", "Chad"],
            ["ME", "Czarnogóra", "Montenegro"],
            ["CZ", "Czechy", "Czechia", 1],
            ["DK", "Dania", "Denmark", 1],
            ["DM", "Dominika", "Dominica"],
            ["DO", "Dominikana", "Dominican Republic"],
            ["DJ", "Dżibuti", "Djibouti"],
            ["EG", "Egipt", "Egypt"],
            ["EC", "Ekwador", "Ecuador"],
            ["ER", "Erytrea", "Eritrea"],
            ["EE", "Estonia", "Estonia", 1],
            ["ET", "Etiopia", "Ethiopia"],
            ["FK", "Falklandy", "Falkland Islands (Malvinas)"],
            ["FJ", "Fidżi Republika", "Fiji"],
            ["PH", "Filipiny", "Philippines"],
            ["FI", "Finlandia", "Finland", 1], 
            ["TF", "Francuskie Terytorium Południowe", "French Southern Territories"],
            ["FR", "Francja", "France", 1],
            ["GA", "Gabon", "Gabon"],
            ["GM", "Gambia", "Gambia"],
            ["GH", "Ghana", "Ghana"],
            ["GI", "Gibraltar", "Gibraltar"],
            ["GR", "Grecja", "Greece", 1],
            ["GD", "Grenada", "Grenada"],
            ["GL", "Grenlandia", "Greenland"],
            ["GE", "Gruzja", "Georgia"],
            ["GU", "Guam", "Guam"],
            ["GY", "Gujana", "Guyana"],
            ["GT", "Gwatemala", "Guatemala"],
            ["GN", "Gwinea", "Guinea"],
            ["GQ", "Gwinea Równikowa", "Equatorial Guinea"],
            ["GW", "Gwinea-Bissau", "Guinea-Bissau"],
            ["HT", "Haiti", "Haiti"],
            ["ES", "Hiszpania", "Spain", 1],
            ["HN", "Honduras", "Honduras"],
            ["HK", "Hongkong", "Hong Kong"],
            ["IN", "Indie", "India"],
            ["ID", "Indonezja", "Indonesia"],
            ["IQ", "Irak", "Iraq"],
            ["IR", "Iran", "Iran, Islamic Republic of"],
            ["IE", "Irlandia", "Ireland", 1],
            ["IS", "Islandia", "Iceland"],
            ["IL", "Izrael", "Israel"],
            ["JM", "Jamajka", "Jamaica"],
            ["JP", "Japonia", "Japan"],
            ["YE", "Jemen", "Yemen"],
            ["JO", "Jordania", "Jordan"],
            ["KY", "Kajmany", "Cayman Islands"],
            ["KH", "Kambodża", "Cambodia"],
            ["CM", "Kamerun", "Cameroon"],
            ["CA", "Kanada", "Canada"],
            ["QA", "Katar", "Qatar"],
            ["KZ", "Kazachstan", "Kazakhstan"],
            ["KE", "Kenia", "Kenya"],
            ["KG", "Kirgistan", "Kyrgyztan"],
            ["KI", "Kiribati", "Kiribati"],
            ["CO", "Kolumbia", "Colombia"],
            ["KM", "Komory", "Comoros"],
            ["CG", "Kongo", "Congo (Rep.)"],
            ["CD", "Kongo, Republika Demokratyczna", "Congo (Dem. Rep.)"],
            ["KP", "Koreańska Republika Ludowo-Demokratyczna", "Korea, Democratic People’s Republic of"],
            ["XK", "Kosowo", "Kosovo"],
            ["CR", "Kostaryka", "Costa Rica"],
            ["CU", "Kuba", "Cuba"],
            ["KW", "Kuwejt", "Kuwait"],
            ["LA", "Laos", "Lao, People’s Democratic Republic of"],
            ["LS", "Lesotho", "Lesotho"],
            ["LB", "Liban", "Lebanon"],
            ["LR", "Liberia", "Liberia"],
            ["LY", "Libia", "Libyan Arab Jamahiriya"],
            ["LI", "Liechtenstein", "Liechtenstein"],
            ["LT", "Litwa", "Lithuania", 1],
            ["LU", "Luksemburg", "Luxembourg", 1],
            ["LV", "Łotwa", "Latvia", 1],
            ["MK", "Macedonia Północna", "North Macedonia"],
            ["MG", "Madagaskar", "Madagascar"],
            ["YT", "Majotta", "Mayotte"],
            ["MO", "Makau", "Macao"],
            ["MW", "Malawi", "Malawi"],
            ["MV", "Malediwy", "Maldives"],
            ["MY", "Malezja", "Malaysia"],
            ["ML", "Mali", "Mali"],
            ["MT", "Malta", "Malta", 1],
            ["MP", "Mariany Północne", "Northern Mariana Islands"],
            ["MA", "Maroko", "Morocco"],
            ["MR", "Mauretania", "Mauritania"],
            ["MU", "Mauritius", "Mauritius"],
            ["MX", "Meksyk", "Mexico"],
            ["XL", "Melilla", "Melilla"],
            ["FM", "Mikronezja", "Micronesia, Federal States of"],
            ["MD", "Mołdawia", "Moldova, Republic of"],
            ["MN", "Mongolia", "Mongolia"],
            ["MS", "Montserrat", "Montserrat"],
            ["MZ", "Mozambik", "Mozambique"],
            ["MM", "Myanmar (Burma)", "Myanmar"],
            ["NA", "Namibia", "Namibia"],
            ["NR", "Nauru", "Nauru"],
            ["NP", "Nepal", "Nepal"],
            ["NL", "Niderlandy", "Netherlands", 1],
            ["DE", "Niemcy", "Germany", 1],
            ["NE", "Niger", "Niger"],
            ["NG", "Nigeria", "Nigeria"],
            ["NI", "Nikaragua", "Nicaragua"],
            ["NU", "Niue", "Niue"],
            ["NF", "Norfolk", "Norfolk Island"],
            ["NO", "Norwegia", "Norway"],
            ["NC", "Nowa Kaledonia", "New Caledonia"],
            ["NZ", "Nowa Zelandia", "New Zealand"],
            ["OM", "Oman", "Oman"],
            ["PK", "Pakistan", "Pakistan"],
            ["PW", "Palau", "Palau"],
            ["PA", "Panama", "Panama"],
            ["PG", "Papua Nowa Gwinea", "Papua New Guinea"],
            ["PY", "Paragwaj", "Paraguay"],
            ["PE", "Peru", "Peru"],
            ["PN", "Pitcairn", "Pitcairn"],
            ["PF", "Polinezja Francuska", "French Polynesia"],
            ["PL", "Polska", "Poland", 1, 1],
            ["ZA", "Południowa Afryka", "South Africa"],
            ["PT", "Portugalia", "Portugal", 1],
            ["KR", "Republika Korei", "Korea, Republic of"],
            ["RU", "Rosja", "Russian Federation"],
            ["RW", "Rwanda", "Rwanda"],
            ["BL", "Saint Barthelemy", "Saint Barthelemy"],
            ["RO", "Rumunia", "Romania", 1],
            ["SV", "Salwador", "EI Salvador"],
            ["WS", "Samoa", "Samoa"],
            ["AS", "Samoa Amerykańskie", "American Samoa"],
            ["SM", "San Marino", "San Marino"],
            ["SN", "Senegal", "Senegal"],
            ["XS", "Serbia", "Serbia"],
            ["SC", "Seszele", "Seychelles"],
            ["SL", "Sierra Leone", "Sierra Leone"],
            ["SG", "Singapur", "Singapore"],
            ["SZ", "Suazi", "Swaziland"],
            ["SK", "Słowacja", "Slovakia", 1],
            ["SI", "Słowenia", "Slovenia", 1],
            ["SO", "Somalia", "Somalia"],
            ["LK", "Sri Lanka", "Sri Lanka"],
            ["US", "Stany Zjedn. Ameryki", "United States of America"],
            ["SD", "Sudan", "Sudan"],
            ["SS", "Sudan Południowy", "South Sudan"],
            ["SR", "Surinam", "Suriname"],
            ["SY", "Syria", "Syrian Arab Republic"],
            ["CH", "Szwajcaria", "Switzerland"],
            ["SE", "Szwecja", "Sweden", 1],
            ["TJ", "Tadżykistan", "Tajikistan"],
            ["TH", "Tajlandia", "Thailand"],
            ["TW", "Tajwan", "Taiwan, Provice of China"],
            ["TZ", "Tanzania", "Tanzania, United Republic of."],
            ["TG", "Togo", "Togo"],
            ["TK", "Tokelau", "Tokelau"],
            ["TO", "Tonga", "Tonga"],
            ["TT", "Trynidad i Tobago", "Trinidad and Tobago"],
            ["TN", "Tunezja", "Tunisia"],
            ["TR", "Turcja", "Turkey"],
            ["TM", "Turkmenistan", "Turkmenistan"],
            ["TC", "Wyspy Turks i Caicos", "Turks and Caicos Islands"],
            ["TV", "Tuvalu", "Tuvalu"],
            ["UG", "Uganda", "Uganda"],
            ["UA", "Ukraina", "Ukraine"],
            ["UY", "Urugwaj", "Uruguay"],
            ["UZ", "Uzbekistan", "Uzbekistan"],
            ["VU", "Vanuatu", "Vanuatu"],
            ["WF", "Wallis i Futuna", "WalIis and Futuna Islands"],
            ["VA", "Watykan", "Vatican City State"],
            ["VE", "Wenezuela", "Venezuela"],
            ["HU", "Węgry", "Hungary", 1],
            ["GB", "Wielka Brytania", "United Kingdom"],
            ["VN", "Wietnam", "Viet - Nam"],
            ["IT", "Włochy", "Italy", 1],
            ["TL", "Wschodni Timor", "Timor Leste"],
            ["CI", "Wyb.Kości Słoniowej", "Cote D’Ivoire"],
            ["BV", "Wyspa Bouveta", "Bouvet Island"],
            ["CX", "Wyspa Bożego Narodzenia", "Christmas Islands"],
            ["CK", "Wyspy Cooka", "Cook Islands"],
            ["VI", "Wyspy Dziewicze-USA", "Virgin Islands (USA)"],
            ["VG", "Wyspy Dziewicze-W.B", "Virgin Islands (British)"],
            ["HM", "Wyspy Heard i McDonald", "Heard and McDonald Islands"],
            ["CC", "Wyspy Kokosowe (Keelinga)", "Cocos (Keeling) Islands"],
            ["FO", "Wyspy Owcze", "Faroe Islands"],
            ["MH", "Wyspy Marshalla", "Marshall Islands"],
            ["SB", "Wyspy Salomona", "Solomon Islands"],
            ["SX", "Wyspa Sint Maarten (część holenderska wyspy)", "Sint Maarten (Dutch part)"],
            ["ST", "Wyspy Św.Tomasza i Książęca", "Sao Tome and Principe"],
            ["ZM", "Zambia", "Zambia"],
            ["CV", "Zielony Przylądek", "Cape Verde"],
            ["ZW", "Zimbabwe", "Zimbabwe"],
            ["AE", "Zjedn.Emiraty Arabskie", "United Arab Emirates"],
            [ "XI", "Zjednoczone Królestwo (Irlandia Północna)", "United Kingdom (Northern Ireland)"],
        ];
    }
    
};
